//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlycuahang
{
    using System;
    using System.Collections.Generic;
    
    public partial class thongkehoadonnhaphang
    {
        public string mahd { get; set; }
        public string manv { get; set; }
        public string mancc { get; set; }
        public System.DateTime ngaylap { get; set; }
        public decimal tongtien { get; set; }
    }
}
