//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlycuahang
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewhoadonnhaphang
    {
        public string mahd { get; set; }
        public string manv { get; set; }
        public string tenncc { get; set; }
        public string diachi { get; set; }
        public string email { get; set; }
        public string sdt { get; set; }
        public string madh { get; set; }
        public string tendh { get; set; }
        public decimal gianhap { get; set; }
        public int soluong { get; set; }
        public Nullable<decimal> thanhtien { get; set; }
        public decimal tongtien { get; set; }
        public System.DateTime ngaylap { get; set; }
    }
}
